# Generated by Django 5.2.13 on 2026-04-22 17:02

import django.utils.timezone
import ulid_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElGitSource',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('gitee', 'Gitee'), ('gitlab', 'GitLab')], max_length=32, verbose_name='平台类型')),
                ('repo_url', models.URLField(verbose_name='仓库地址')),
                ('token', models.CharField(max_length=512, verbose_name='Access Token')),
                ('default_branch', models.CharField(default='main', max_length=128, verbose_name='默认分支')),
                ('description', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '仓库源',
                'verbose_name_plural': '仓库源',
                'db_table': 'el_git_source',
                'ordering': ['-created_at'],
            },
        ),
    ]
