# Generated by Django 5.2 on 2025-09-28 17:12

import django.utils.timezone
import ulid_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCommandsRecord',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='命令名称')),
                ('status', models.CharField(choices=[('success', '成功'), ('fail', '失败')], help_text='命令执行状态：success表示成功，fail表示失败', max_length=50, verbose_name='执行状态')),
            ],
            options={
                'verbose_name': '初始化数据执行记录',
                'verbose_name_plural': '初始化数据执行记录',
                'db_table': 'el_system_command_record',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='el_system_c_name_6e41af_idx'), models.Index(fields=['status'], name='el_system_c_status_fd71f6_idx')],
            },
        ),
    ]
