# Generated by Django 5.2 on 2026-03-20 15:19

import django.db.models.deletion
import django.utils.timezone
import ulid_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='菜单标识')),
                ('path', models.CharField(max_length=100, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, max_length=100, verbose_name='组件名称')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('title', models.CharField(max_length=50, verbose_name='显示标题')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('keep_alive', models.BooleanField(default=False, verbose_name='是否缓存')),
                ('permission', models.CharField(blank=True, max_length=100, verbose_name='权限标识')),
                ('menu_type', models.CharField(choices=[('directory', '目录'), ('menu', '菜单'), ('button', '按钮')], default='menu', max_length=20, verbose_name='菜单类型')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'el_system_menu',
                'ordering': ['order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='权限名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='权限标识')),
                ('type', models.CharField(choices=[('menu', '菜单'), ('button', '按钮'), ('api', 'API')], default='menu', max_length=20, verbose_name='权限类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'el_system_permission',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='角色标识')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认角色')),
                ('menus', models.ManyToManyField(blank=True, to='system.menu', verbose_name='菜单')),
                ('permissions', models.ManyToManyField(blank=True, to='system.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'el_system_role',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SystemCommandsRecord',
        ),
    ]
