# Generated by Django 5.2 on 2026-03-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system', '0002_menu_permission_role_delete_systemcommandsrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_menus', to='auth.group', verbose_name='用户组')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.menu', verbose_name='菜单')),
            ],
            options={
                'verbose_name': '组菜单关联',
                'verbose_name_plural': '组菜单关联',
                'db_table': 'el_system_group_menu',
                'unique_together': {('group', 'menu')},
            },
        ),
    ]
