# Generated by Django 5.2 on 2026-03-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_groupmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='role',
            name='menus',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
