# Generated by Django 5.2 on 2026-03-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system', '0004_remove_role_permissions_remove_role_menus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMenu',
            new_name='ElGroupMenu',
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='ElMenu',
        ),
    ]
