# Generated by Django 5.2.13 on 2026-04-19 19:03

import django.utils.timezone
import ulid_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElSandboxInstance',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128, verbose_name='沙箱名称')),
                ('type', models.CharField(choices=[('localdocker', '本地 Docker'), ('remotedocker', '远程 Docker'), ('localsystem', '本地系统'), ('remotesystem', '远程系统')], max_length=20, verbose_name='沙箱类型')),
                ('root_path', models.CharField(max_length=512, verbose_name='沙箱文件根目录')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '未激活'), ('error', '错误')], default='inactive', max_length=20, verbose_name='状态')),
                ('metadata', models.JSONField(default=dict, verbose_name='配置元信息')),
            ],
            options={
                'verbose_name': '沙箱实例',
                'verbose_name_plural': '沙箱实例',
                'db_table': 'el_sandbox_instance',
            },
        ),
    ]
