# Generated by Django 5.2.13 on 2026-04-22 17:29

import django.db.models.deletion
import django.utils.timezone
import ulid_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0002_elagentexecutionlog_git_commit_hash_and_more'),
        ('git_source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElTask',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('description', models.TextField(default='', verbose_name='描述')),
                ('source_branch', models.CharField(default='main', max_length=128, verbose_name='源分支')),
                ('status', models.CharField(choices=[('open', '进行中'), ('closed', '已关闭')], default='open', max_length=32, verbose_name='状态')),
                ('git_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='git_source.elgitsource', verbose_name='仓库源')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'el_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElTaskConversation',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('comment_type', models.CharField(choices=[('user', '用户指令'), ('ai', 'AI 回复'), ('system', '系统通知')], max_length=32, verbose_name='类型')),
                ('agent_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='关联 Agent 编码')),
                ('execution_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.elagentexecutionlog', verbose_name='关联执行日志')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='task.eltask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '任务对话',
                'verbose_name_plural': '任务对话',
                'db_table': 'el_task_conversation',
                'ordering': ['created_at'],
            },
        ),
    ]
