# Generated by Django 5.2.13 on 2026-04-23 15:16

import django.db.models.deletion
import django.utils.timezone
import ulid_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_elagentexecutionlog_git_commit_hash_and_more'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElTaskMemory',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('thread_id', models.CharField(max_length=128, verbose_name='线程 ID')),
                ('execution_order', models.PositiveIntegerField(verbose_name='执行顺序号')),
                ('summary', models.TextField(verbose_name='Agent 执行摘要')),
                ('commit_message', models.TextField(blank=True, null=True, verbose_name='Git 提交信息')),
                ('pr_url', models.URLField(blank=True, null=True, verbose_name='PR 地址')),
                ('commit_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='Commit Hash')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=16, verbose_name='执行状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_memories', to='agent.elagent', verbose_name='执行 Agent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='task.eltask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '任务记忆',
                'verbose_name_plural': '任务记忆',
                'db_table': 'el_task_memory',
                'ordering': ['execution_order'],
            },
        ),
    ]
