# Generated by Django 5.2.13 on 2026-04-20 16:01

import django.db.models.deletion
import django.utils.timezone
import ulid_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElAgent',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Agent 编码')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Agent 名称')),
                ('description', models.TextField(default='', verbose_name='功能描述')),
                ('system_prompt', models.TextField(default='', verbose_name='系统提示词')),
                ('model', models.CharField(default='', max_length=128, verbose_name='LLM 模型')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('deleted', '已删除')], db_index=True, default='active', max_length=32, verbose_name='状态')),
                ('metadata', models.JSONField(default=dict, verbose_name='扩展配置')),
            ],
            options={
                'verbose_name': 'Agent 配置',
                'verbose_name_plural': 'Agent 配置',
                'db_table': 'el_agent',
            },
        ),
        migrations.CreateModel(
            name='ElAgentExecutionLog',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('thread_id', models.CharField(db_index=True, max_length=128, verbose_name='线程 ID')),
                ('status', models.CharField(choices=[('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='running', max_length=32, verbose_name='执行状态')),
                ('events', models.JSONField(default=list, verbose_name='原始事件流')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='执行结果')),
                ('error_message', models.TextField(default='', verbose_name='错误信息')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='agent.elagent', verbose_name='关联 Agent')),
            ],
            options={
                'verbose_name': 'Agent 执行日志',
                'verbose_name_plural': 'Agent 执行日志',
                'db_table': 'el_agent_execution_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
