# Generated by Django 5.2.13 on 2026-04-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elagentexecutionlog',
            name='git_commit_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='最后一次 commit hash'),
        ),
        migrations.AddField(
            model_name='elagentexecutionlog',
            name='git_pr_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='PR 编号'),
        ),
        migrations.AddField(
            model_name='elagentexecutionlog',
            name='git_pr_url',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='PR 地址'),
        ),
    ]
