# Generated by Django 5.2.13 on 2026-04-24 18:00

import django.db.models.deletion
from django.db import migrations, models


def migrate_model_to_fk(apps, schema_editor):
    """
    将 ElAgent 的 model CharField 字符串值映射到 ElLLMModel FK。
    根据旧的 model_code 字符串在 PRESET_PROVIDERS 中查找对应的 ElLLMModel，
    找不到则保持 null。
    """
    from llm.constants import PRESET_PROVIDERS

    ElAgent = apps.get_model("agent", "ElAgent")
    ElLLMModel = apps.get_model("llm", "ElLLMModel")

    # 构建 model_code -> ElLLMModel 的映射
    code_to_model = {}
    for code, data in PRESET_PROVIDERS.items():
        provider = apps.get_model("llm", "ElLLMProvider").objects.filter(code=code).first()
        if provider:
            for m in data["models"]:
                model_obj = ElLLMModel.objects.filter(
                    provider=provider, model_code=m["model_code"]
                ).first()
                if model_obj:
                    code_to_model[m["model_code"]] = model_obj

    # 迁移所有已有 ElAgent 记录
    for agent in ElAgent.objects.all():
        if agent.model:
            new_model = code_to_model.get(agent.model)
            if new_model:
                agent.llm_model = new_model
                agent.save(update_fields=["llm_model"])


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_elagentexecutionlog_git_commit_hash_and_more'),
        ('llm', '0001_initial'),
    ]

    operations = [
        # 1. 先新增 FK 字段（允许为空）
        migrations.AddField(
            model_name='elagent',
            name='llm_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='llm.elllmmodel', verbose_name='LLM 模型'),
        ),
        # 2. 数据迁移：将旧 model 字符串映射到新 llm_model FK
        migrations.RunPython(migrate_model_to_fk, migrations.RunPython.noop),
        # 3. 删除旧的 model CharField
        migrations.RemoveField(
            model_name='elagent',
            name='model',
        ),
    ]
