# Generated by Django 5.2.13 on 2026-04-25 18:10

import django.db.models.deletion
import django.utils.timezone
import ulid_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_agent_model_to_llm_model_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElExecutorConfig',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executor_code', models.CharField(max_length=50, verbose_name='执行器编码')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('timeout', models.IntegerField(default=3600, verbose_name='超时时间（秒）')),
                ('cli_path', models.CharField(blank=True, default='', help_text='沙箱内 CLI 绝对路径（若不在 PATH 中）', max_length=500, verbose_name='CLI 路径')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor_configs', to='agent.elagent', verbose_name='关联 Agent')),
            ],
            options={
                'verbose_name': 'CLI 执行器配置',
                'verbose_name_plural': 'CLI 执行器配置',
                'db_table': 'el_executor_config',
                'ordering': ['created_at'],
                'unique_together': {('agent', 'executor_code')},
            },
        ),
    ]
