# Generated by Django 5.2.13 on 2026-04-25 20:23

import django.db.models.deletion
import django.utils.timezone
import ulid_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_elexecutorconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElExecutor',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='执行器编码')),
                ('name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('timeout', models.IntegerField(default=3600, verbose_name='超时时间（秒）')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展配置')),
            ],
            options={
                'verbose_name': 'CLI 执行器',
                'verbose_name_plural': 'CLI 执行器',
                'db_table': 'el_agent_executor',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='elagent',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='agent.elexecutor', verbose_name='CLI 执行器'),
        ),
        migrations.DeleteModel(
            name='ElExecutorConfig',
        ),
    ]
