# Generated by Django 5.2.13 on 2026-04-28 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_elexecutor_elagent_executor_delete_elexecutorconfig'),
        ('sandbox', '0002_remove_elsandboxinstance_root_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='elagent',
            name='sandbox_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='sandbox.elsandboxinstance', verbose_name='绑定沙箱实例'),
        ),
    ]
