# Generated by Django 5.2.13 on 2026-04-28 19:05

import django.db.models.deletion
from django.db import migrations, models


def populate_sandbox_instance(apps, schema_editor):
    """将已有的 Agent 绑定到第一个可用的沙箱实例。"""
    ElAgent = apps.get_model('agent', 'ElAgent')
    ElSandboxInstance = apps.get_model('sandbox', 'ElSandboxInstance')
    first_sandbox = ElSandboxInstance.objects.first()
    if first_sandbox:
        ElAgent.objects.filter(sandbox_instance__isnull=True).update(sandbox_instance=first_sandbox)


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_elexecutor_elagent_executor_delete_elexecutorconfig'),
        ('sandbox', '0002_remove_elsandboxinstance_root_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='elagent',
            name='sandbox_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='sandbox.elsandboxinstance', verbose_name='绑定沙箱实例'),
        ),
        migrations.RunPython(populate_sandbox_instance, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='elagent',
            name='sandbox_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='sandbox.elsandboxinstance', verbose_name='绑定沙箱实例'),
        ),
    ]
