# Generated by Django 5.2.13 on 2026-04-24 17:38

import django.db.models.deletion
import django.utils.timezone
import ulid_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElLLMProvider',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='供应商编码')),
                ('name', models.CharField(max_length=128, verbose_name='供应商名称')),
                ('base_url', models.CharField(default='', max_length=512, verbose_name='API 基础地址')),
                ('api_key_encrypted', models.TextField(default='', verbose_name='API 密钥（加密）')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
            ],
            options={
                'verbose_name': 'LLM 供应商',
                'verbose_name_plural': 'LLM 供应商',
                'db_table': 'el_llm_provider',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElLLMModel',
            fields=[
                ('id', ulid_django.models.ULIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_code', models.CharField(max_length=128, verbose_name='模型编码')),
                ('display_name', models.CharField(default='', max_length=255, verbose_name='显示名称')),
                ('context_window', models.IntegerField(default=0, verbose_name='上下文窗口（tokens）')),
                ('max_output_tokens', models.IntegerField(default=0, verbose_name='最大输出 tokens')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否可用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='llm.elllmprovider', verbose_name='所属供应商')),
            ],
            options={
                'verbose_name': 'LLM 模型',
                'verbose_name_plural': 'LLM 模型',
                'db_table': 'el_llm_model',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('provider', 'model_code')},
            },
        ),
    ]
